[GH-205]Fix issue for allowing snap host access.
When attach an exported snapshot to another host, a error:

storops.exception.UnitySnapAlreadyPromotedException: The system was not
able to promote a snapshot because it is already promoted. (Error
Code:0x6000bdc)

will be throw. this commit will fix it by using the modify action